#ifndef _TC_NUKLEAR_H_
#define _TC_NUKLEAR_H_

#include <stdarg.h>
#include <SDL.h>

#define NK_INCLUDE_FIXED_TYPES
#define NK_INCLUDE_STANDARD_IO
#define NK_INCLUDE_STANDARD_VARARGS
#define NK_INCLUDE_DEFAULT_ALLOCATOR
#define NK_INCLUDE_VERTEX_BUFFER_OUTPUT
#define NK_INCLUDE_FONT_BAKING
#define NK_INCLUDE_COMMAND_USERDATA
#define NK_INCLUDE_DEFAULT_FONT

#include "nuklear.h"

#endif /* _TC_NUKLEAR_H_ */
